services:
  nihomeBackend:
    image: nihome31042025-backend
    container_name: nihome31042025-backend
    build:
      context: .
      dockerfile: ./nihomebackend/Dockerfile
    stdin_open: true
    tty: true
    working_dir: /app
    command: dotnet watch --non-interactive run --urls=http://0.0.0.0:5043
    ports:
      - "5043:5043"
    restart: unless-stopped
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5043
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=NihomeDB;User Id=sa;Password=Nihome@31042025;TrustServerCertificate=True;
    volumes:
      - ./nihomebackend:/app
      - ./nihomeweb:/nihomeweb
      - nihomebackend_bin:/app/bin
      - nihomebackend_obj:/app/obj
      - nihome_process_assets:/app/wwwroot/process-assets
      - nihomeweb_node_modules:/nihomeweb/node_modules
      - nihomeweb_dist:/nihomeweb/dist
      - nuget_packages:/root/.nuget/packages
    networks:
      - nihome-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: nihome31042025-sqlserver
    environment:
      SA_PASSWORD: "Nihome@31042025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - nihome-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  nihomeweb_node_modules:
  nihomeweb_dist:
  nihomebackend_bin:
  nihomebackend_obj:
  nihome_process_assets:
  nuget_packages:
  sqlserver_data:

networks:
  nihome-network:
    driver: bridge
