/**
 * Single source of truth mapping admin route prefixes to the permission code
 * required to access them. Consumed by both <RequirePermission> route wrappers
 * in App.tsx and the sidebar filter in AdminLayout so a route never appears in
 * navigation that the user cannot actually open.
 *
 * Keep codes in sync with rbac-defaults.json. Wildcard-bearing roles
 * (SUPER_ADMIN, ADMIN, BGD) get all of these automatically through pattern
 * expansion at the server.
 */
export const ADMIN_PERMS = {
  dashboard: "dashboard.view",
  notifications: "dashboard.view",
  activities: "content.activities.view",
  activitiesManage: "content.activities.manage",
  news: "content.news.view",
  newsManage: "content.news.manage",
  projects: "content.projects.view",
  projectsManage: "content.projects.manage",
  services: "content.services.view",
  servicesManage: "content.services.manage",
  contacts: "contacts.view",
  contactsManage: "contacts.manage",
  leads: "crm.leads.view",
  leadsManage: "crm.leads.manage",
  leadsConvert: "crm.leads.convert",
  leadsViewAll: "crm.leads.view.all",
  customers: "crm.customers.view",
  customersManage: "crm.customers.manage",
  customersExport: "crm.customers.export",
  customersViewAll: "crm.customers.view.all",
  opportunities: "crm.opportunities.view",
  opportunitiesManage: "crm.opportunities.manage",
  opportunitiesViewAll: "crm.opportunities.view.all",
  quotes: "crm.quotes.view",
  quotesManage: "crm.quotes.manage",
  quotesApprove: "crm.quotes.approve",
  quotesSend: "crm.quotes.send",
  quotesViewAll: "crm.quotes.view.all",
  capabilityDocs: "crm.capability-docs.view",
  capabilityDocsManage: "crm.capability-docs.manage",
  tenders: "crm.tenders.view",
  tendersManage: "crm.tenders.manage",
  tendersMarkResult: "crm.tenders.mark-result",
  surveys: "crm.surveys.view",
  surveysManage: "crm.surveys.manage",
  contracts: "crm.contracts.view",
  contractsManage: "crm.contracts.manage",
  contractsViewAll: "crm.contracts.view.all",
  designProjects: "design.projects.view",
  designProjectsManage: "design.projects.manage",
  permits: "permit.checklists.view",
  permitsManage: "permit.checklists.manage",
  designConcepts: "design.concepts.view",
  designConceptsManage: "design.concepts.manage",
  designConceptsFinalize: "design.concepts.finalize",
  designBasic: "design.basic.view",
  designBasicManage: "design.basic.manage",
  designBasicApprove: "design.basic.approve",
  designShop: "design.shop.view",
  designShopManage: "design.shop.manage",
  designShopApprove: "design.shop.approve",
  designRevisions: "design.revisions.view",
  designRevisionsManage: "design.revisions.manage",
  designIfc: "design.ifc.view",
  designIfcManage: "design.ifc.manage",
  designIfcRelease: "design.ifc.release",
  constructionTasks: "construction.tasks.view",
  constructionTasksManage: "construction.tasks.manage",
  constructionDiary: "construction.diary.view",
  constructionDiaryManage: "construction.diary.manage",
  constructionDiaryConfirm: "construction.diary.confirm",
  constructionPunch: "construction.punch.view",
  constructionPunchManage: "construction.punch.manage",
  constructionPunchVerify: "construction.punch.verify",
  constructionAcceptance: "construction.acceptance.view",
  constructionAcceptanceManage: "construction.acceptance.manage",
  constructionAcceptanceApprove: "construction.acceptance.approve",
  constructionAsBuilt: "construction.asbuilt.view",
  constructionAsBuiltManage: "construction.asbuilt.manage",
  constructionAsBuiltApprove: "construction.asbuilt.approve",
  recruitment: "recruitment.applications.view",
  recruitmentPositions: "recruitment.positions.view",
  recruitmentOptions: "recruitment.options.view",
  activityCategories: "content.activity-categories.view",
  activityCategoriesManage: "content.activity-categories.manage",
  newsCategories: "content.news-categories.view",
  newsCategoriesManage: "content.news-categories.manage",
  categories: "content.project-categories.view",
  about: "content.about.view",
  logos: "content.logos.view",
  processes: "processes.view",
  processesManage: "processes.manage",
  settings: "system.settings.view",
  translations: "content.translations.view",
  translationsManage: "content.translations.manage",
  emailTemplates: "system.settings.manage",
  activityLog: "system.audit.view",
  users: "users.view",
  usersManage: "users.manage",
  rbacRoles: "rbac.roles.view",
  rbacRolesManage: "rbac.roles.manage",
  masterData: "master-data.view",
  masterDataManage: "master-data.manage",
  workflow: "workflow.view",
  workflowManage: "workflow.manage",
} as const;
